import Header from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-dark300 text-font w-screen h-screen overflow-hidden'>
        <Header/>
        {children}
        </body>
    </html>
  )
}
